us-east-1: "US East (N. Virginia)"
us-east-2: "US East (Ohio)"
us-west-1: "US West (N. California)"
us-west-2: "US West (Oregon)"
ca-central-1: "Canada (Central)"
eu-central-1: "EU (Frankfurt)"
eu-central-2: "EU (Zurich)"
eu-west-1: "EU (Ireland)"
eu-west-2: "EU (London)"
eu-west-3: "EU (Paris)"
eu-north-1: "EU (Stockholm)"
eu-south-1: "EU (Milan)"
eu-south-2: "EU (Spain)"
ap-south-1: "Asia Pacific (Mumbai)"
ap-south-2: "Asia Pacific (Hyderabad)"
ap-southeast-1: "Asia Pacific (Singapore)"
ap-southeast-2: "Asia Pacific (Sydney)"
ap-southeast-3: "Asia Pacific (Jakarta)"
ap-southeast-4: "Asia Pacific (Melbourne)"
ap-northeast-1: "Asia Pacific (Tokyo)"
ap-northeast-2: "Asia Pacific (Seoul)"
ap-northeast-3: "Asia Pacific (Osaka)"
ap-east-1: "Asia Pacific (Hong Kong)"
me-south-1: "Middle East (Bahrain)"
me-central-1: "Middle East (UAE)"
af-south-1: "Africa (Cape Town)"
sa-east-1: "South America (São Paulo)"

